version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-node-browsers
      - image: lordj7x/circleci:node-jdk-rub-pip-v1.4
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Downloading ZAP test
          command: wget https://github.com/zaproxy/zaproxy/releases/download/2.4.3/ZAP_2.4.3_Linux.tar.gz
      - run: sudo tar zxf ZAP_2.4.3_Linux.tar.gz  --no-same-owner
      - run: sudo ln -s ./ZAP_2.4.3 /opt/zap
      - run: set -x
      - run:
          name: Downloading and setting up ZED init files
          command: sudo wget -O ./zap.sh https://raw.githubusercontent.com/stelligent/zap/master/packer/roles/zap/files/zap-init.sh
      - run: sudo chmod +x ./zap.sh
      - run:
          name: Starting up... O W A S P  Z A P  P O C
          command: sudo ./zap.sh start
      - run:
          name: Checking O W A S P  Z A P  status...
          command: sudo ./zap.sh status
      - run:
          name: Installing PENN TEST TOOLS...
          command: |
             echo "Installing ZAP API via PIP"
             pip install python-owasp-zap-v2.4
             pip install flask
