version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-node-browsers
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Downloading ZAP test
          command: wget https://github.com/zaproxy/zaproxy/releases/download/2.4.3/ZAP_2.4.3_Linux.tar.gz
      - run: tar zxf ZAP_2.4.3_Linux.tar.gz -C /opt --no-same-owner
      - run: ln -s /opt/ZAP_2.4.3 /opt/zap
      - run:
          name: Downloading and setting up ZED init files
          command: wget -q -O /etc/init.d/zap https://raw.githubusercontent.com/stelligent/zap/master/packer/roles/zap/files/zap-init.sh
      - run:
          name: Starting up... O W A S P  Z A P  P O C
          command: /etc/init.d/zap start
